name: Android APK (Buildozer)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
      - '**.kv'
      - 'buildozer.spec'
      - 'manifest_additions.xml'
      - '.github/workflows/android-build.yml'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          pwd
          ls -la

      - name: Ensure filenames
        run: |
          set -e
          # dashaman.py or dashaman (10).py -> main.py
          if [ -f "dashaman.py" ] && [ ! -f "main.py" ]; then mv "dashaman.py" "main.py"; fi
          if [ -f "dashaman (10).py" ] && [ ! -f "main.py" ]; then mv "dashaman (10).py" "main.py"; fi
          # service_hotword (2).py -> service_hotword.py
          if [ -f "service_hotword (2).py" ] && [ ! -f "service_hotword.py" ]; then mv "service_hotword (2).py" "service_hotword.py"; fi
          echo "Files after rename:"
          ls -la

      - name: Patch buildozer.spec (requirements/permissions/services/manifest)
        run: |
          set -e
          if [ ! -f buildozer.spec ]; then
            echo "::error::buildozer.spec not found. Add it to the repo root."
            exit 1
          fi
          sed -i 's|^requirements *=.*|requirements = python3,kivy,pyjnius,plyer|' buildozer.spec || true
          if ! grep -q '^requirements' buildozer.spec; then echo 'requirements = python3,kivy,pyjnius,plyer' >> buildozer.spec; fi
          sed -i 's|^android.permissions *=.*|android.permissions = RECORD_AUDIO,INTERNET,FOREGROUND_SERVICE|' buildozer.spec || true
          if ! grep -q '^android.permissions' buildozer.spec; then echo 'android.permissions = RECORD_AUDIO,INTERNET,FOREGROUND_SERVICE' >> buildozer.spec; fi
          sed -i 's|^services *=.*|services = hotword:service_hotword.py|' buildozer.spec || true
          if ! grep -q '^services' buildozer.spec; then echo 'services = hotword:service_hotword.py' >> buildozer.spec; fi
          sed -i 's|^android.add_src *=.*|android.add_src = manifest_additions.xml|' buildozer.spec || true
          if ! grep -q '^android.add_src' buildozer.spec; then echo 'android.add_src = manifest_additions.xml' >> buildozer.spec; fi
          echo "===== buildozer.spec (head) ====="
          head -n 80 buildozer.spec

      - name: Use Buildozer action
        uses: ArtemSBulgakov/buildozer-action@v1.3
        with:
          buildozer_version: 1.5.0
          command: buildozer android debug
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashman-apk
          path: bin/*.apk
d: warn
