name: Android APK (Buildozer)

on:
  workflow_dispatch:    # позволяет запускать вручную из Actions
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.kv'
      - 'buildozer.spec'
      - 'manifest_additions.xml'
      - '.github/workflows/android-build.yml'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure filenames
        run: |
          set -e
          if [ -f "dashaman.py" ] && [ ! -f "main.py" ]; then mv "dashaman.py" "main.py"; fi
          if [ -f "service_hotword (2).py" ] && [ ! -f "service_hotword.py" ]; then mv "service_hotword (2).py" "service_hotword.py"; fi
          ls -la

      - name: Build with Buildozer
        uses: artemsb1982/buildozer-action@v1.2.0
        with:
          buildozer_version: 1.5.0
          command: buildozer -v android debug
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dashman-apk
          path: bin/*.apk
          if-no-files-found: warn
